# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-19 10:26
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200515_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('4x6', '4x6'), ('5x7', '5x7'), ('8x8', '8x8'), ('11x4', '11x4'), ('12x12', '12x12'), ('8×10', '8×10'), ('5×15', '5×15'), ('12×36', '12×36'), ('8×24', '8×24'), ('16×20', '16×20'), ('20×30', '20×30')], max_length=55),
        ),
    ]
