# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-26 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200520_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
