# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-27 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20200526_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catergorie',
            field=models.CharField(choices=[('paper', 'Paper'), ('canvas', 'Canvas')], default='canvas', max_length=10),
        ),
    ]
