# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-27 20:13
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_catergorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, '4x6'), (2, '5x7'), (3, '8x8'), (4, '11x4'), (5, '12x12'), (6, '8×10'), (7, '5×15'), (8, '12×36'), (9, '8×24'), (10, '16×20'), (11, '20×30')], max_length=23),
        ),
    ]
