# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-28 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20200528_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('4x4', '4x6'), ('5x7', '5x7'), ('8x8', '8x8'), ('11x4', '11x4'), ('12x12', '12x12'), ('8x10', '8×10'), ('5x15', '5×15'), ('12x36', '12×36'), ('8x24', '8×24'), ('16x20', '16×20'), ('20x30', '20×30')], default=1, max_length=10),
        ),
    ]
