# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-19 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('catergorie', models.CharField(choices=[('paper', 'Paper'), ('canvas', 'Canvas')], default='canvas', max_length=10)),
            ],
        ),
    ]
